server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spp_tsks
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update